# Generated by Django 4.2.7 on 2024-09-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0005_delete_roompeaklowestvalues"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="marked_by",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="marked_by_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
