# Generated by Django 4.2.7 on 2024-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0006_alert_marked_by_alert_marked_by_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="viewed_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
