# Generated by Django 4.2.7 on 2024-09-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0007_alert_viewed_at_alert_viewed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="buildings",
            field=models.ManyToManyField(
                related_name="clusters", to="GTRE_APPLICATION.building"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="main_admins",
            field=models.ManyToManyField(
                blank=True, related_name="clusters", to="GTRE_APPLICATION.mainadmin"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="power_modules",
            field=models.ManyToManyField(
                related_name="clusters", to="GTRE_APPLICATION.powermodule"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="sub_admins",
            field=models.ManyToManyField(
                blank=True, related_name="clusters", to="GTRE_APPLICATION.subadmin"
            ),
        ),
    ]
