# Generated by Django 4.2.7 on 2024-09-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GsmModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("module_name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(default="0.0.0.0")),
                ("topic_name", models.CharField(default="", max_length=255)),
                ("numbers", models.JSONField(default=list)),
                (
                    "mobile_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MainAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MqttDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(default="0.0.0.0")),
                ("topic_name", models.CharField(default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("temperature", models.FloatField(blank=True, null=True)),
                ("humidity", models.FloatField(blank=True, null=True)),
                ("doorState", models.BooleanField(blank=True, null=True)),
                ("floodState", models.BooleanField(blank=True, null=True)),
                ("pirState", models.BooleanField(blank=True, null=True)),
                ("gasState", models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SubAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("username", models.CharField(max_length=250, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("suspended", models.BooleanField(default=False)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="GTRE_APPLICATION.mainadmin",
                    ),
                ),
                (
                    "building",
                    models.ManyToManyField(
                        blank=True,
                        related_name="sub_admins",
                        to="GTRE_APPLICATION.building",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(default="0.0.0.0")),
                ("topic_name", models.CharField(default="", max_length=255)),
                ("temperature_threshold", models.FloatField(default=0)),
                ("humidity_threshold", models.FloatField(default=0)),
                ("door_state_threshold", models.CharField(max_length=100)),
                ("flood_state_threshold", models.CharField(max_length=100)),
                ("pir_state_threshold", models.CharField(max_length=100)),
                ("gas_state_threshold", models.CharField(max_length=100)),
                ("interval", models.IntegerField(default=0)),
                ("temperature_alerts", models.CharField(blank=True, max_length=255)),
                ("humidity_alerts", models.CharField(blank=True, max_length=255)),
                ("door_alerts", models.CharField(blank=True, max_length=255)),
                ("flood_alerts", models.CharField(blank=True, max_length=255)),
                ("pir_alerts", models.CharField(blank=True, max_length=255)),
                ("gas_alerts", models.CharField(blank=True, max_length=255)),
                ("gsm_alert", models.CharField(default="disable", max_length=10)),
                ("gsm_numbers", models.JSONField(blank=True, default=list)),
                (
                    "main_admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms",
                        to="GTRE_APPLICATION.mainadmin",
                    ),
                ),
                (
                    "sensor_data",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms",
                        to="GTRE_APPLICATION.sensordata",
                    ),
                ),
                (
                    "sub_admins",
                    models.ManyToManyField(
                        blank=True, related_name="rooms", to="GTRE_APPLICATION.subadmin"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("ip_address", models.GenericIPAddressField(default="0.0.0.0")),
                ("topic_name", models.CharField(default="", max_length=255)),
                ("ct1", models.FloatField(default=0.0)),
                ("ct2", models.FloatField(default=0.0)),
                ("ct3", models.FloatField(default=0.0)),
                ("ct4", models.FloatField(default=0.0)),
                ("ct1correspondingname", models.CharField(max_length=100)),
                ("ct2correspondingname", models.CharField(max_length=100)),
                ("ct3correspondingname", models.CharField(max_length=100)),
                ("ct4correspondingname", models.CharField(max_length=100)),
                (
                    "buildings",
                    models.ManyToManyField(
                        blank=True,
                        related_name="power_modules",
                        to="GTRE_APPLICATION.building",
                    ),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        related_name="powermodule", to="GTRE_APPLICATION.room"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PowerData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ct1", models.FloatField()),
                ("ct2", models.FloatField()),
                ("ct3", models.FloatField()),
                ("ct4", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "power_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GTRE_APPLICATION.powermodule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mainadmin",
            name="room",
            field=models.ManyToManyField(blank=True, to="GTRE_APPLICATION.room"),
        ),
        migrations.AddField(
            model_name="mainadmin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Cluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "rooms",
                    models.ManyToManyField(
                        related_name="cluster", to="GTRE_APPLICATION.room"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="building",
            name="rooms",
            field=models.ManyToManyField(
                related_name="buildings", to="GTRE_APPLICATION.room"
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "custom_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("type", models.CharField(max_length=50)),
                ("message", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("viewed", models.BooleanField(default=False)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="GTRE_APPLICATION.room",
                    ),
                ),
            ],
        ),
    ]
