# Generated by Django 4.2.7 on 2024-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="alert_mqtt_device",
            field=models.ManyToManyField(
                related_name="MqttDevice", to="GTRE_APPLICATION.mqttdevice"
            ),
        ),
    ]
