# Generated by Django 4.2.7 on 2024-09-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0003_alter_room_alert_mqtt_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomPeakLowestValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peak_temperature", models.FloatField(blank=True, null=True)),
                ("peak_temperature_time", models.DateTimeField(blank=True, null=True)),
                ("lowest_temperature", models.FloatField(blank=True, null=True)),
                (
                    "lowest_temperature_time",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("peak_humidity", models.FloatField(blank=True, null=True)),
                ("peak_humidity_time", models.DateTimeField(blank=True, null=True)),
                ("lowest_humidity", models.FloatField(blank=True, null=True)),
                ("lowest_humidity_time", models.DateTimeField(blank=True, null=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peak_lowest_values",
                        to="GTRE_APPLICATION.room",
                    ),
                ),
            ],
        ),
    ]
