# Generated by Django 4.2.7 on 2024-09-18 06:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0004_roompeaklowestvalues"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RoomPeakLowestValues",
        ),
    ]
