# Generated by Django 4.2.7 on 2024-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0008_cluster_buildings_cluster_main_admins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="door_sensors",
            field=models.ManyToManyField(
                blank=True, related_name="door_clusters", to="GTRE_APPLICATION.room"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="flood_sensors",
            field=models.ManyToManyField(
                blank=True, related_name="flood_clusters", to="GTRE_APPLICATION.room"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="gas_sensors",
            field=models.ManyToManyField(
                blank=True, related_name="gas_clusters", to="GTRE_APPLICATION.room"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="humidity_sensors",
            field=models.ManyToManyField(
                blank=True, related_name="humidity_clusters", to="GTRE_APPLICATION.room"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="pir_sensors",
            field=models.ManyToManyField(
                blank=True, related_name="pir_clusters", to="GTRE_APPLICATION.room"
            ),
        ),
        migrations.AddField(
            model_name="cluster",
            name="temperature_sensors",
            field=models.ManyToManyField(
                blank=True,
                related_name="temperature_clusters",
                to="GTRE_APPLICATION.room",
            ),
        ),
    ]
