# Generated by Django 4.2.7 on 2024-09-25 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "GTRE_APPLICATION",
            "0009_cluster_door_sensors_cluster_flood_sensors_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cluster",
            name="door_sensors",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="flood_sensors",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="gas_sensors",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="humidity_sensors",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="pir_sensors",
        ),
        migrations.RemoveField(
            model_name="cluster",
            name="temperature_sensors",
        ),
    ]
