# Generated by Django 4.2.7 on 2024-09-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0010_remove_cluster_door_sensors_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="rooms",
            field=models.ManyToManyField(
                related_name="clusters", to="GTRE_APPLICATION.room"
            ),
        ),
    ]
