# Generated by Django 4.2.7 on 2024-09-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0011_alter_cluster_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="main_admins",
            field=models.ManyToManyField(
                related_name="clusters", to="GTRE_APPLICATION.mainadmin"
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="sub_admins",
            field=models.ManyToManyField(
                related_name="clusters", to="GTRE_APPLICATION.subadmin"
            ),
        ),
    ]
