# Generated by Django 4.2.7 on 2024-09-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GTRE_APPLICATION", "0012_alter_cluster_main_admins_alter_cluster_sub_admins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cluster",
            name="main_admins",
            field=models.ManyToManyField(
                blank=True, related_name="clusters", to="GTRE_APPLICATION.mainadmin"
            ),
        ),
        migrations.AlterField(
            model_name="cluster",
            name="sub_admins",
            field=models.ManyToManyField(
                blank=True, related_name="clusters", to="GTRE_APPLICATION.subadmin"
            ),
        ),
    ]
