# Generated by Django 5.0.4 on 2024-11-17 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTRE_APPLICATION', '0014_pinneddashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnedDashboard',
        ),
    ]
