# Generated by Django 5.0.4 on 2024-11-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GTRE_APPLICATION', '0016_pinneddashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PinnedDashboard',
        ),
    ]
